(in-package #:clgfw)

;;; MOUSE BUTTONS
(defconstant mouse-button-left 'mouse-button-left)
(defconstant mouse-button-right 'mouse-button-right)
(defconstant mouse-button-middle 'mouse-button-middle)

;;; KEY
(defconstant key-quote           'key-quote)
(defconstant key-comma           'key-comma)
(defconstant key-minus           'key-minus)
(defconstant key-period          'key-period)
(defconstant key-slash           'key-slash)
(defconstant key-zero            'key-zero)
(defconstant key-one             'key-one)
(defconstant key-two             'key-two)
(defconstant key-three           'key-three)
(defconstant key-four            'key-four)
(defconstant key-five            'key-five)
(defconstant key-six             'key-six)
(defconstant key-seven           'key-seven)
(defconstant key-eight           'key-eight)
(defconstant key-nine            'key-nine)
(defconstant key-semicolon       'key-semicolon)
(defconstant key-equal           'key-equal)
(defconstant key-a               'key-a)
(defconstant key-b               'key-b)
(defconstant key-c               'key-c)
(defconstant key-d               'key-d)
(defconstant key-e               'key-e)
(defconstant key-f               'key-f)
(defconstant key-g               'key-g)
(defconstant key-h               'key-h)
(defconstant key-i               'key-i)
(defconstant key-j               'key-j)
(defconstant key-k               'key-k)
(defconstant key-l               'key-l)
(defconstant key-m               'key-m)
(defconstant key-n               'key-n)
(defconstant key-o               'key-o)
(defconstant key-p               'key-p)
(defconstant key-q               'key-q)
(defconstant key-r               'key-r)
(defconstant key-s               'key-s)
(defconstant key-t               'key-t)
(defconstant key-u               'key-u)
(defconstant key-v               'key-v)
(defconstant key-w               'key-w)
(defconstant key-x               'key-x)
(defconstant key-y               'key-y)
(defconstant key-z               'key-z)
(defconstant key-left-bracket    'key-left-bracket)
(defconstant key-backslash       'key-backslash)
(defconstant key-right-bracket   'key-right-bracket)
(defconstant key-backtick        'key-backtick)
(defconstant key-space           'key-space)
(defconstant key-escape          'key-escape)
(defconstant key-enter           'key-enter)
(defconstant key-tab             'key-tab)
(defconstant key-backspace       'key-backspace)
(defconstant key-insert          'key-insert)
(defconstant key-delete          'key-delete)
(defconstant key-right           'key-right)
(defconstant key-left            'key-left)
(defconstant key-down            'key-down)
(defconstant key-up              'key-up)
(defconstant key-page-up         'key-page-up)
(defconstant key-page-down       'key-page-down)
(defconstant key-home            'key-home)
(defconstant key-end             'key-end)
(defconstant key-caps-lock       'key-caps-lock)
(defconstant key-scroll-lock     'key-scroll-lock)
(defconstant key-num-lock        'key-num-lock)
(defconstant key-print-screen    'key-print-screen)
(defconstant key-pause           'key-pause)
(defconstant key-f1              'key-f1)
(defconstant key-f2              'key-f2)
(defconstant key-f3              'key-f3)
(defconstant key-f4              'key-f4)
(defconstant key-f5              'key-f5)
(defconstant key-f6              'key-f6)
(defconstant key-f7              'key-f7)
(defconstant key-f8              'key-f8)
(defconstant key-f9              'key-f9)
(defconstant key-f10             'key-f10)
(defconstant key-f11             'key-f11)
(defconstant key-f12             'key-f12)
(defconstant key-left-shift      'key-left-shift)
(defconstant key-right-shift     'key-right-shift)
(defconstant key-left-control    'key-left-control)
(defconstant key-right-control   'key-right-control)
(defconstant key-left-alt        'key-left-alt)
(defconstant key-right-alt       'key-right-alt)
(defconstant key-left-super      'key-left-super)
(defconstant key-right-super     'key-right-super)
(defconstant key-left-meta       'key-left-meta)
(defconstant key-right-meta      'key-right-meta)
(defconstant key-left-hyper      'key-left-hyper)
(defconstant key-right-hyper     'key-right-hyper)
(defconstant key-kb-menu         'key-kb-menu)
(defconstant key-keypad-0        'key-keypad-0)
(defconstant key-keypad-1        'key-keypad-1)
(defconstant key-keypad-2        'key-keypad-2)
(defconstant key-keypad-3        'key-keypad-3)
(defconstant key-keypad-4        'key-keypad-4)
(defconstant key-keypad-5        'key-keypad-5)
(defconstant key-keypad-6        'key-keypad-6)
(defconstant key-keypad-7        'key-keypad-7)
(defconstant key-keypad-8        'key-keypad-8)
(defconstant key-keypad-9        'key-keypad-9)
(defconstant key-keypad-decimal  'key-keypad-decimal)
(defconstant key-keypad-divide   'key-keypad-divide)
(defconstant key-keypad-multiply 'key-keypad-multiply)
(defconstant key-keypad-subtract 'key-keypad-subtract)
(defconstant key-keypad-add      'key-keypad-add)
(defconstant key-keypad-enter    'key-keypad-enter)
(defconstant key-keypad-equal    'key-keypad-equal)

(deftype key ()
  '(member key-quote key-comma key-minus key-period         
    key-slash key-zero key-one key-two key-three          
    key-four key-five key-six key-seven key-eight          
    key-nine key-semicolon key-equal key-a key-b              
    key-c key-d key-e key-f key-g              
    key-h key-i key-j key-k key-l              
    key-m key-n key-o key-p key-q              
    key-r key-s key-t key-u key-v              
    key-w key-x key-y key-z key-left-bracket   
    key-backslash key-right-bracket key-backtick key-space key-escape         
    key-enter key-tab key-backspace key-insert key-delete         
    key-right key-left key-down key-up key-page-up        
    key-page-down key-home key-end key-caps-lock key-scroll-lock    
    key-num-lock key-print-screen key-pause key-f1 key-f2             
    key-f3 key-f4 key-f5 key-f6 key-f7             
    key-f8 key-f9 key-f10 key-f11 key-f12            
    key-left-shift key-right-shift key-left-control key-right-control
    key-left-alt key-right-alt key-left-super key-right-super key-left-meta      
    key-right-meta key-left-hyper key-right-hyper key-kb-menu key-keypad-0       
    key-keypad-1 key-keypad-2 key-keypad-3 key-keypad-4 key-keypad-5       
    key-keypad-6 key-keypad-7 key-keypad-8 key-keypad-9 key-keypad-decimal 
    key-keypad-divide key-keypad-multiply key-keypad-subtract
    key-keypad-add key-keypad-enter key-keypad-equal))

(declaim (ftype (function (key) character)))
(defun key->char (key)
  "Returns the corresponding character if possible or nil otherwise"
  (case key
    (key-a #\a)
    (key-b #\b)
    (key-c #\c)
    (key-d #\d)
    (key-e #\e)
    (key-f #\f)
    (key-g #\g)
    (key-h #\h)
    (key-i #\i)
    (key-j #\j)
    (key-k #\k)
    (key-l #\l)
    (key-m #\m)
    (key-n #\n)
    (key-o #\o)
    (key-p #\p)
    (key-q #\q)
    (key-r #\r)
    (key-s #\s)
    (key-t #\t)
    (key-u #\u)
    (key-v #\v)
    (key-w #\w)
    (key-x #\x)
    (key-y #\y)
    (key-z #\z)

    (key-zero  #\0)
    (key-one   #\1)
    (key-two   #\2)
    (key-three #\3)
    (key-four  #\4)
    (key-five  #\5)
    (key-six   #\6)
    (key-seven #\7)
    (key-eight #\8)
    (key-nine  #\9)

    (key-quote        #\')
    (key-comma        #\,)
    (key-minus        #\-)
    (key-period       #\.)
    (key-slash        #\/)
    (key-semicolon    #\;)
    (key-equal        #\=)
    (key-left-bracket #\[)
    (key-right-bracket #\])
    (key-backslash    #\\)
    (key-backtick     #\`)
    (key-space        #\Space)

    (key-escape #\Esc)))


